### PR TITLE
chore(ci): add change log ci

### PR DESCRIPTION
**Pull request by jasondeng1997**
#### What type of PR is this?
<!--
Add one of the following kinds:

fix https://github.com/kitex-contrib/codec-hessian2/issues/7

### CODE REVIEW

**Review by Lvnszn — COMMENTED** [review]
please add in action

**Comment by jasondeng1997** [comment]
#7

**Comment by jasondeng1997** [comment]
add in action done

**Comment by jasondeng1997** [comment]
Please merge this chagelogs first

**Review by YangruiEmma — APPROVED** [review]

**Pull request merged**
